cars = ['chevrolet', 'toyota', 'nissan', 'vw', 'hyundai', 'dodge']
print("Print list in its original order:")
print(cars)
print()
print("Print list in alphabetical order using sorted()")
print(sorted(cars))
print()
print("Print list in its original order:")
print(cars)
print()
print("Print list in reverse alphabetical order using sorted()")
print(sorted(cars,reverse=True))
print()
print("Print list in its original order:")
print(cars)
print()
print("Change order of list using reverse()")
cars.reverse()
print(cars)
print()
print("Change order of list, once again, using reverse()")
cars.reverse()
print(cars)
print()
print("Change list so it's in alphabetical order using sort()")
cars.sort()
print(cars)
print()
print("Reverse alphabetize list using sort()")
cars.sort(reverse=True)
print(cars)
