cities = ['monterey', 'sydney', 'paris', 'new york', 'seattle']
print(cities)
print()
print(sorted(cities))
print()
print(cities)
print()
print(sorted(cities, reverse=True))
print()
cities.sort()
print(cities)
print()
cities.reverse()
print(cities)
cities.reverse()
print(cities)
print()
print("Lets start fresh")
cities = ['monterey', 'sydney', 'paris', 'new york', 'seattle']
cities.sort()
print(cities)
cities.reverse()
print(cities)

